name: snapshot

env:
  MAVEN_OPTS: "-Xmx2G -XX:+ExitOnOutOfMemoryError -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3"

on:
  workflow_call:
    secrets:
      CLOUDSMITH_USERNAME:
        required: true
      CLOUDSMITH_PASSWORD:
        required: true
      CLOUDSMITH_CENTRAL_PASSWORD:
        required: true
    inputs:
      maven_args:
        description: The arguments to pass to all Maven commands when building the code
        required: false
        default: '-DskipTests=true'
        type: string
      maven_version:
        description: The Maven version used for builds
        required: false
        default: '3.9.16'
        type: string
      os:
        description: The OS used
        required: false
        default: 'ubuntu-22.04'
        type: string
      jdk:
        description: The JDK used
        required: false
        default: '21'
        type: string
      jdk-distribution:
        description: The JDK distribution used
        required: false
        default: 'temurin'
        type: string
      timeout-minutes:
        description: 'timeout-minutes used by the builds (defaults to 360)'
        required: false
        default: 360
        type: number
      goal:
        description: The Maven goal(s) used
        required: false
        default: 'deploy'
        type: string
      failure-upload-path:
        description: A file, directory or wildcard pattern that describes what to upload on failure
        required: false
        type: string

jobs:
  snapshot:
    runs-on: ${{ inputs.os }}
    if: ${{ github.actor != 'dependabot[bot]' }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.jdk }}
          distribution: ${{ inputs.jdk-distribution }}
          cache: 'maven'
      - name: Configure Cloudsmith credentials
        uses: s4u/maven-settings-action@v4.0.0
        with:
          githubServer: false
          # This will cause generated settings.xml will have:
          # - Profile with auto-generated ID
          # - Make the profile enable by default
          # - Add `<repositories>` and `<pluginRepositories>` under the profile
          #
          # At the time of writing, the "username" actually not needed for downloading artifact from Cloudsmith.
          # Because of this, the "central" only need password. The "username" attribute set because it is required by
          # maven-settings-action.
          #
          # The "cloudsmith" need to be declared here, and will be used by actual `pom.xml`'s <distributionManagement/>
          servers: |
            [
              {"id": "central", "username": "-", "password": "${{ secrets.CLOUDSMITH_CENTRAL_PASSWORD }}"},
              {"id": "cloudsmith", "username": "${{ secrets.CLOUDSMITH_USERNAME }}", "password": "${{ secrets.CLOUDSMITH_PASSWORD }}"}
            ]
          # As mentioned above, only `<distributionManagement />` needs "cloudsmith".
          repositories: |
            [
              {
                "id": "central", 
                "name": "Central repository at Cloudsmith",
                "url": "https://dl.cloudsmith.io/basic/killbill/oss/maven/",
                "releases": { "enabled": "true", "updatePolicy": "always" },
                "snapshots": { "enabled": "true", "updatePolicy": "always" }
              }
            ]
          pluginRepositories: |
            [
              {
                "id": "central", 
                "name": "Central repository at Cloudsmith",
                "url": "https://dl.cloudsmith.io/basic/killbill/oss/maven/",
                "releases": { "enabled": "true", "updatePolicy": "always" },
                "snapshots": { "enabled": "true", "updatePolicy": "always" }
              }
            ]
      - name: Set up Maven
        run: mvn --errors --batch-mode --show-version wrapper:wrapper "-Dmaven=${{ inputs.maven_version }}"
      - name: Set new version
        run: |
          current_version_with_snapshot=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          current_version_without_snapshot=${current_version_with_snapshot%SNAPSHOT*}
          snapshot_version="${current_version_without_snapshot}$(git rev-parse --short "$GITHUB_SHA")-SNAPSHOT"
          ./mvnw versions:set -DnewVersion=${snapshot_version}
          echo "::notice ::Version is ${snapshot_version}"
      - name: Deploy artifacts
        run: ./mvnw --errors --batch-mode --show-version ${{ inputs.maven_args }} ${{ inputs.goal }}
      - name: Upload artifact on failure
        uses: actions/upload-artifact@v7
        if: failure() && inputs.failure-upload-path != ''
        with:
          name: failure-${{ inputs.os }}-${{ inputs.jdk }}-${{ inputs.jdk-distribution }}
          path: ${{ inputs.failure-upload-path }}
